spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect:
        hibernate: org.hibernate.dialect.MySQL8Dialect